select
fr.DESCRIPTION as FR_DESCRIPTION,fr.CREATED_BY as FR_CREATED_BY,fr.CREATED_ON as FR_CREATED_ON,fr.ALLOW_MODIFY as FR_ALLOW_MODIFY, 
fr.ACTIVE as FR_ACTIVE,fr.STYPE as FR_STYPE, fr.LC as FR_LC, fr.LC_VERSION  as FR_LC_VERSION, fr.SS as FR_SS,
fr.EFFECTIVE_TILL as FR_EFFECTIVE_TILL ,fr.EFFECTIVE_FROM as FR_EFFECTIVE_FROM,fr.INHERIT_AU as FR_INHERIT_AU,fr.LOG_HS as FR_LOG_HUS, 
fr.SP_LC as FR_SP_LC,fr.SP_LC_VERSION as FR_SP_LC_VERSION,fr.CONTEXT as FR_CONTEXT,fr.ALLOW_ANY_IP as FR_ALLOW_ANY_IP,
fr.LAST_COMMENT as FR_LAST_COMMENT,fr.UNIQUE_ID as FR_UNIQUE_ID,fr.IMG_LINK as FR_IMG_LINK,TRANSFERRED as FR_TRANSFERRED, fr.FR as FR_FR,fr.FR_VERSION,


sp.FR as SP_FR,sp.FR_VERSION as SP_FR_VERSION,sp.SP_VALUE,sp.DESCRIPTION as SP_DESCRIPTION,sp.LAST_STATUS_CHANGE as SP_LAST_STATUS_CHANGE,sp.CREATED_BY as SP_CREATED_BY,
sp.CREATED_ON as SP_CREATED_ON,sp.LC as SP_LC,sp.LC_VERSION as SP_LC_VERSION,sp.SS as SP_SS,sp.EFFECTIVE_TILL as SP_EFFECTIVE_TILL,sp.EFFECTIVE_FROM as SP_EFFECTIVE_FROM,
sp.STYPE as SP_STYPE,sp.ALLOW_MODIFY as SP_ALLOW_MODIFY,sp.ACTIVE as SP_ACTIVE,sp.LOG_HS as SP_LOG_HS,sp.CONTEXT as SP_CONTEXT,sp.UNIQUE_ID as SP_UNIQUE_ID,
sp.ALLOW_ANY_IP as SP_ALLOW_ANY_IP,sp.LAST_COMMENT as SP_LAST_COMMENT,sp.HAS_ADHOC_APPROVAL as SP_HAS_ADHOC_APPROVAL,sp.MA as SP_MA,sp.SP_VERSION ,sp.SP,
		
		
spic.SP as SPIC_SP ,spic.SP_VERSION as SPIC_SP_VERSION,spic.IC,spic.IC_SHORT_DESC,spic.ICNODE,spic.IP_VERSION as SPIC_IP_VERSION,spic.DESCRIPTION as SPIC_DESCRIPTION,
spic.WINSIZE_X as SPIC_WINSIZE,WINSIZE_Y as SPIC_WINSIZE_Y,spic.IS_PROTECTED as SPIC_IS_PROTECTED,spic.HIDDEN as SPIC_HIDDEN,spic.LAST_COMMENT as SPIC_LAST_COMMENT,
spic.LOG_HS as SPIC_LOG_HS,spic.ALLOW_MODIFY as SPIC_ALLOW_MODIFY,spic.ACTIVE as SPIC_ACTIVE,spic.LC as SPIC_LC,spic.LC_VERSION as SPIC_LC_VERSION,spic.SS as SPIC_SS,
spic.UNIQUE_ID as SPIC_UNIQUE_ID,spic.IMG_LINK as SPIC_IMG_LINK,DSP_TITLE as SPIC_DSP_TITLE,FREQ_TP as SPIC_FREQ_TP


FROM [OpcenterRDnL].[RndSuite].[RndtFr] as fr
join [OpcenterRDnL].[RndSuite].[RndtSp] as sp ON fr.FR = sp.FR and fr.FR_VERSION = sp.FR_VERSION
join [OpcenterRDnL].[RndSuite].[RndtSpIc] as spic ON sp.SP = spic.SP
where sp.FR = 11 and sp.FR_VERSION = 6.0000
